### ISSUE TITLE
less strict version requirements?

### ISSUE THREAD

**Issue by mathause** [IAMconsortium/pyam#840]
Pyam has relatively strict version pins - this makes it difficult to install alongside other packages (or in an existing environment). Would you consider relaxing these requirements?

Many packages in the scientific stack follow [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) or [SPEC-00](https://scientific-python.org/specs/spec-0000/) (which are very similar). I ran your requirements through [xarrays interpretation of the rules](https://github.com/pydata/xarray/blob/main/ci/min_deps_check.py), which suggests that your requirements for python, numpy, pandas and xlsxwriter should be relaxed.

```
Package           Required             Policy               Status
----------------- -------------------- -------------------- ------
python            3.10    (2021-10-04) 3.9     (2020-10-05) > (!)
iam-units         2020.4  (2020-06-07) 2022.10 (2022-10-27) <
ixmp4             0.8     (2024-03-20) 0.8     (2024-03-20) =
matplotlib        3.6     (2022-09-16) 3.7     (2023-02-14) <
numpy             1.26    (2023-09-17) 1.23    (2022-06-23) > (!)
openpyxl          3.1     (2023-01-31) 3.1     (2023-01-31) =
pandas            2.1     (2023-08-30) 1.5     (2022-09-19) > (!)
Pint              0.13    (2020-06-25) 0.20    (2022-10-25) <
PyYAML            6.0     (2021-10-16) 6.0     (2021-10-16) =
scipy             1.10    (2023-01-04) 1.10    (2023-01-04) =
seaborn           0.11    (2020-09-08) 0.12    (2022-09-06) <
six               1.16    (2021-05-05) 1.16    (2021-05-05) =
wquantiles        0.6     (2021-05-26) 0.6     (2021-05-26) =
xlsxwriter        3.1     (2023-04-27) 3.0     (2021-08-10) > (!)
```

(NOTE: you require xlswriter 3.2, but this is not yet available on conda-forge, https://github.com/conda-forge/xlsxwriter-feedstock/pulls)

edit: added `enviroment.yml` file I used to run min_deps_check.py

<details>

```yaml
name: pyam-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
 - python=3.10
 - iam-units=2020.4
 - ixmp4=0.8
 - matplotlib=3.6
 - numpy=1.26
 - openpyxl=3.1
 - pandas=2.1
 - Pint=0.13
 - PyYAML=6.0
 - scipy=1.10
 - seaborn=0.11
 - six=1.16
 - wquantiles=0.6
 - xlsxwriter=3.1
```

</details>
